### ISSUE TITLE
After converting to one dicom I got this error, and the conversion is stopped.

### ISSUE THREAD

**Issue by al3ms** [amine0110/Medical-Conversions#3]
ITK ERROR: GDCMImageIO(0000018218CDF610): A Floating point buffer was passed but the stored pixel type was not specified.This is currently not supported

**Comment by thisisrick25** [comment]
https://github.com/amine0110/Medical-Conversions/issues/1 you need this.

**Comment by amine0110** [comment]
Thanks @thisisrick25
