### ISSUE TITLE
Error in sequence numbering order of slices in volumetric MRI scans [ nii to DICOM ]

### ISSUE THREAD

**Issue by iAmIlluminati** [amine0110/Medical-Conversions#5]
I can convert from nii to dicom, and it recognises as a volumetric scan in DICOM viewers. **But the sequence number is random, the slices are coming in random order when viewing the DICOM.** 

Source nii : https://drive.google.com/file/d/1vBVcCIQqwyO4CT5iKdYSjFeVx7PlYGvl/view?usp=sharing
Output DICOM : https://drive.google.com/drive/folders/1cwkc5l-HZLAAUac6vAKB08rU932TiO98?usp=sharing

**Comment by iAmIlluminati** [comment]
Generation Code
![image](https://user-images.githubusercontent.com/49597171/222536717-32db0bc2-1f76-4126-bf37-b6f20e50523f.png)

**Comment by amine0110** [comment]
The code works correctly! I have never find a problem with it. I tried running the conversion on your case and it works.

![image](https://user-images.githubusercontent.com/37108394/222685067-c009d7fe-1cd2-4195-8463-129f603dc905.png)

I am opening it on ITK-snap without any issues!

Here are the dicoms of your nifti file (after conversion using the app): https://www.dropbox.com/s/framkjuvwq916u4/BraTS20_training.zip?dl=0
